eureka:
  instance:
    hostname: localhost
  client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

server:
  port: 3333
spring:
  application:
    name: subscription
  config:
    import: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dxdeployer
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
      
application:
  security:
    jwt:
      access:
        secret: '8dbi283dg328n92d4u39r2ijeodu3h02ox0d923u0dsujdd8sadgs8a8dgasd2ude03209u23uj'
        expiration: 86400000

springdoc:
  api-docs:
    path: /api/v1/account/v3/api-docs
  swagger-ui:
    path: /api/v1/account/swagger-ui.html

application:
  config:
    accounts-url: http://localhost:1111/api/v1/account
    project-url: http://localhost:2222/api/v1/project
    payment-url: http://localhost:4444/api/v1/payment
    notification-url: http://localhost:5555/api/v1/notification